#ifndef WISDOM_GATEWAY_CODES_H
#define WISDOM_GATEWAY_CODES_H

typedef enum _gateway_codes {
	GATEWAY_ERROR,
	GATEWAY_COMMAND,
	PACKED_DATA
} GATEWAY_CODE_T;

typedef enum _gateway_commands {
	GATEWAY_START,
	GATEWAY_STOP
} GATEWAY_COMMAND_T;

#endif // WISDOM_GATEWAY_CODES_H
