#ifndef SHT30_WISDOM_CONSTANTS_H
#define SHT30_WISDOM_CONSTANTS_H

typedef enum sht30_commands_e {
	SHT30_SSDA_CS_HIGH,
	SHT30_SSDA_CS_MED,
	SHT30_SSDA_CS_LOW,
	SHT30_SSDA_HIGH,
	SHT30_SSDA_MED,
	SHT30_SSDA_LOW,
	SHT30_COMMANDS_MAX
} sht30_command_t;

uint8_t sht30_command_lookup[SHT30_COMMANDS_MAX][2] {

}


#endif // SHT30_WISDOM_CONSTANTS_H
